# Generated by Django 2.1.7 on 2019-04-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('data_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='데이터 ID')),
                ('data_cnt', models.PositiveIntegerField(default=0, verbose_name='데이터 갯수')),
                ('mean', models.FloatField(default=0.0, verbose_name='평균')),
                ('maximum', models.FloatField(default=0.0, verbose_name='최대값')),
                ('minimum', models.FloatField(default=0.0, verbose_name='최소값')),
                ('use_duration', models.BooleanField(default=False, verbose_name='선택자')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DurationInfo',
            fields=[
                ('datainfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='informations.DataInfo')),
            ],
            options={
                'abstract': False,
            },
            bases=('informations.datainfo',),
        ),
        migrations.CreateModel(
            name='ProductivityInfo',
            fields=[
                ('datainfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='informations.DataInfo')),
            ],
            options={
                'abstract': False,
            },
            bases=('informations.datainfo',),
        ),
    ]
