# Generated by Django 2.1.7 on 2019-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0002_auto_20190223_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('data_cnt', models.PositiveIntegerField(default=0, verbose_name='데이터 갯수')),
                ('mean', models.FloatField(default=0.0, verbose_name='평균')),
                ('maximum', models.FloatField(default=0.0, verbose_name='최대값')),
                ('minimum', models.FloatField(default=0.0, verbose_name='최소값')),
                ('description', models.TextField(blank=True, verbose_name='기간 설명')),
                ('work_package', models.ManyToManyField(related_name='durations', to='managements.WorkPackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductivityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('data_cnt', models.PositiveIntegerField(default=0, verbose_name='데이터 갯수')),
                ('mean', models.FloatField(default=0.0, verbose_name='평균')),
                ('maximum', models.FloatField(default=0.0, verbose_name='최대값')),
                ('minimum', models.FloatField(default=0.0, verbose_name='최소값')),
                ('description', models.TextField(blank=True, verbose_name='생산성 설명')),
                ('work_package', models.ManyToManyField(related_name='productivities', to='managements.WorkPackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
