# Generated by Django 2.1.7 on 2019-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='work_package',
            field=models.ManyToManyField(related_name='durations', to='managements.WorkPackage'),
        ),
    ]
