# Generated by Django 2.1.7 on 2019-05-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_datainfo_work_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='name',
            field=models.CharField(default='testname', max_length=300, verbose_name='데이터 이름'),
            preserve_default=False,
        ),
    ]
