# Generated by Django 2.1.7 on 2019-02-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_auto_20190225_0337'),
        ('informations', '0002_auto_20190224_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datainfo',
            old_name='duration_flag',
            new_name='use_duration',
        ),
        migrations.RemoveField(
            model_name='durationinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='durationinfo',
            name='work_package',
        ),
        migrations.RemoveField(
            model_name='productivityinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productivityinfo',
            name='work_package',
        ),
        migrations.AddField(
            model_name='datainfo',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='work_package',
            field=models.ManyToManyField(related_name='durations', to='managements.WorkPackage'),
        ),
    ]
