# Generated by Django 2.1.7 on 2019-05-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_datainfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='description',
            field=models.TextField(null=True, verbose_name='설명'),
        ),
    ]
