# Generated by Django 2.1.7 on 2019-02-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('name', models.CharField(max_length=300, verbose_name='액티비티 이름')),
                ('description', models.TextField(blank=True, verbose_name='액티비티 설명')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='기간')),
                ('productivity', models.FloatField(default=0.0, verbose_name='생산성')),
                ('labor_cnt', models.PositiveIntegerField(default=0, verbose_name='인력 총원')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('data_cnt', models.PositiveIntegerField(default=0, verbose_name='데이터 갯수')),
                ('mean', models.FloatField(default=0.0, verbose_name='평균')),
                ('maximum', models.FloatField(default=0.0, verbose_name='최대값')),
                ('minimum', models.FloatField(default=0.0, verbose_name='최소값')),
                ('description', models.TextField(blank=True, verbose_name='기간 설명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Productivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('data_cnt', models.PositiveIntegerField(default=0, verbose_name='데이터 갯수')),
                ('mean', models.FloatField(default=0.0, verbose_name='평균')),
                ('maximum', models.FloatField(default=0.0, verbose_name='최대값')),
                ('minimum', models.FloatField(default=0.0, verbose_name='최소값')),
                ('description', models.TextField(blank=True, verbose_name='생산성 설명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('name', models.CharField(max_length=300, verbose_name='프로젝트 이름')),
                ('description', models.TextField(blank=True, verbose_name='프로젝트 설명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('name', models.CharField(max_length=300, verbose_name='리소스 이름')),
                ('productivity', models.FloatField(default=0.0, verbose_name='생산성')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('package', models.CharField(max_length=300, verbose_name='Work Package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='work_package',
            field=models.ManyToManyField(related_name='resources', to='managements.WorkPackage'),
        ),
        migrations.AddField(
            model_name='productivity',
            name='work_package',
            field=models.ManyToManyField(related_name='productivities', to='managements.WorkPackage'),
        ),
        migrations.AddField(
            model_name='duration',
            name='work_package',
            field=models.ManyToManyField(related_name='durations', to='managements.WorkPackage'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='managements.Project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='managements.Resource'),
        ),
        migrations.AddField(
            model_name='activity',
            name='work_package',
            field=models.ManyToManyField(related_name='activities', to='managements.WorkPackage'),
        ),
    ]
