# Generated by Django 2.1.7 on 2019-02-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='work_package',
        ),
        migrations.RemoveField(
            model_name='productivity',
            name='work_package',
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.DeleteModel(
            name='Productivity',
        ),
    ]
