# Generated by Django 2.1.7 on 2019-03-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpackage',
            old_name='package',
            new_name='package_name',
        ),
        migrations.AlterUniqueTogether(
            name='workpackage',
            unique_together={('package_name', 'parent_package')},
        ),
    ]
