# Generated by Django 2.1.7 on 2019-02-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='parent_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managements.WorkPackage'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='informations.DataInfo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='managements.Resource'),
        ),
    ]
