# Generated by Django 2.1.7 on 2019-05-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannedschedules', '0004_auto_20190508_2334'),
        ('managements', '0002_auto_20190501_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='work_package',
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.CharField(max_length=300, null=True, verbose_name='프로젝트'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='resource',
            field=models.CharField(max_length=300, null=True, verbose_name='리소스'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
