# Generated by Django 2.1.7 on 2019-05-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_auto_20190508_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(null=True, verbose_name='액티비티 설명'),
        ),
    ]
