# Generated by Django 2.1.7 on 2019-05-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_auto_20190514_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='labor_cnt',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='인력 총원'),
        ),
    ]
