# Generated by Django 2.1.7 on 2019-04-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informations', '0002_datainfo_work_package'),
        ('managements', '0002_auto_20190316_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedSchedules',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('activity_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='액티비티 Id')),
                ('wbs_id', models.CharField(max_length=300, verbose_name='WBS Id')),
                ('name', models.CharField(max_length=300, verbose_name='액티비티 이름')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='기간')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='물량')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_schedules', to='informations.DataInfo')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_schedules', to='managements.Resource')),
                ('work_package', models.ManyToManyField(related_name='planned_schedules', to='managements.WorkPackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
