# Generated by Django 2.1.7 on 2019-04-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_datainfo_work_package'),
        ('managements', '0001_initial'),
        ('plannedschedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('is_productivity', models.BooleanField(verbose_name='생산성 사용여부')),
                ('mode', models.SmallIntegerField(verbose_name='모드')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='managements.Activity')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='informations.DataInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
