# Generated by Django 2.1.7 on 2019-04-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannedschedules', '0002_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='plannedschedules.PlannedSchedules'),
        ),
    ]
