# Generated by Django 2.1.7 on 2019-05-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannedschedules', '0003_auto_20190421_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedschedules',
            name='resource',
            field=models.CharField(max_length=300, null=True, verbose_name='리소스'),
        ),
    ]
